name: myDamTrip
favicon: null
layout_spectrum: 0.37855351460166276
typography_spectrum: 0.22191965859383345
title: The Tales of My Dam Trips
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.11565485317260027
  lightness: 0.16496411128900945
  saturation: 0.3105391103308648
  rhythmicContrast: 0.9304322246462107
purpose: []
